const data = `
- Natural sciences:
  - Mathematics
  - Physics:
    - $S Mechanics
  - Chemistry:
    - $S Stochiometry
    - $S Organic Chemistry:
      - $T Alkanes:
        - 1[Methane]
        - 2[Ethane]
        - 3[Propane]
        - 4[Butane]
        - 5[Pentane]
        - 6[Hexane]
        - 7[Heptane]
        - 8[Octane]
        - 9[Nonane]
        - 10[Decane]
      - $T Alkenes:
        - 2[Ethene]
        - 3[Propene]
        - 4[Butene]
        - 5[Pentene]
      - Alkynes
      - Alcohols
      - Phenols
      - Aldehydes
      - Ketones
      - Carboxylic acids
      - Esters
      - Ethers
      - Amines
      - Thiols
      - Disulfides
      - Nitro compounds
  - $S Biochemistry:
    - Cell Biology:
      - Cells
      - Cell types
    - Genetics
    - Biomolecules:
      - Carbohydrates
      - Lipids
      - Proteins
      - Nucleic acids
    - Metabolism:
      - General metabolic pathways
      - Cellular respiration
      - Photosynthesis
      - Replication
      - Transcription
      - Translation
  - $S Biology:
    - Plants and fungi
    - Physiology
`;
