let vocabulary = [
    ["Microcosm", "Small place with same characteristics as larger"],
    ["Clash with/over", "Fight/argue"],
    ["Outright", "Completely/immediately"],
    ["Startlingly", "Surprising+slightly worrying"],
    ["Fundraising", "Collecting money for purpose"],
    ["Better off", "Having more money"],
    ["Tap up", "To make a specific approach to a person considered to be suitable for a professional position."],
    ["Outing", "Short journey"],
    ["Mounting", "Gradually increasing"],
    ["Ingenuity", "Ability to think clever/new ways"],
    ["Justified", "Having good reason"],
    ["Board and lodging", "Food and a place to sleep"],
    ["Syllabus", "A plan showing the subjects or books to be studied"],
    ["Exempt", "(exemption)"],
    ["Glamorous", "Excitingly and specially attractive"],
    ["Single-handed", "Without help from others"],
    ["Foster", "Take care of a child, Encourage the development of ideas/feelings"],
    ["Amid", "In the middle of or surrounded by"],
];