const data = `
- Natural sciences:
  - Mathematics
  - Physics:
    - $S Astronomy
    - $S Rigid body mechanics
    - $S Fluid mechanics
    - $S Electricity and magnetism
    - $S Thermodynamics
    - $S Waves
    - $S Nuclear physics
    - $S Quantum mechanics
  - Chemistry:
    - $S Stochiometry:
      - $T Stochiometry basics:
        - eq(equation)[S(P_i) => S(R_j)]
        - m(mass)[S(m_i=M_i*n_i) = S(m_j=M_j*n_j)]
        - M(molmass)[M_i _ M_j]
        - n(amount of substance, <limiting>)[:(n_i) . :(n_j)]
        - n0[n0_i _ n0_j]
        - Δn[:(Δn_i) _ -:(Δn_j)]
        - n1[n0_i+Δn_i _ n0_j+Δn_j]
        - c[n_i/V _ n_j/V]
      - Other:
        - K=P(c_j)/P(c_i)
        - Ka = [H3O+][A-]/[HA]
        - Kb = [HB+][OH-]/[B]
        - Kw = Ka*Kb = [H3O+][OH-] = 1e-14
        - Ks = [A+][B-]
        - pKa = -lg Ka
        - pKb = -lg Kb
        - pKw = pKa+pKb = pH+pOH = -lg Kw = 14
        - pH = -lg[H3O+]
      - Titration:
        - ...
    - $S Organic Chemistry:
      - $T Legend:
        - (*)[Toxic]
        - TRA[Transparent]
        - W[White]
        - S[Solid]
        - CR[Crystalform]
        - OL[Odorless]
        - PO[Penetration odor]
        - R[Reactive]
        - F[Flammable]
        - B[Burnable]
        - C[Carcinogenic]
        - D[Dizziness]
        - CED[Celebral damages]
      - $T Alkanes (-):
        - _[Melt Boil Color Smell Toxic]
        - 1[-183 -162 TRA OL F*]
        - 2[-183 -89 TRA OL -]
        - 3[-188 -44 - - -]
        - 4[-138 0 - - -]
        - 5[-129 36 - - -]
        - 6[-95 69 - - -]
        - 7[-91 98 - - -]
        - 8[-57 126 - - -]
        - 9[-51 151 - - -]
        - 10[-30 174 - - -]
        - (1)3[-160 -12 - - -]
        - (2-1)4[-160 28 - - -]
        - (2,2-1)3[-16 10 - - -]
      - $T Cycloalkanes (~n):
        - _[Melt Boil Color Smell Toxic]
        - ~3[-128 -33 TRA - F*]
        - ~4[-91 13 - - -]
        - ~5[-94 50 - - -]
        - ~6[6 81 - - -]
      - $T Alkenes:
        - _[Melt Boil Color Smell Toxic]
        - 2=[-169.2 -103.7 - - B]
        - 3=[-185.2 -47.6 - - -]
        - 4=[-185.3 -6.3 - - -]
        - 5=[-165.2 36.1 - - -]
        - 6=[-140 62.8 - - -]
        - 7=[-119 93 - - -]
        - 8=[-101 122 - - -]
        - 9=[-57.5 101 - - -]
        - 10=[-45.5 163 - - -]
        - (2-1)3[-140.4 -6.9 - - -]
        - T4.2[106 0.3 - - -]
      - $T Alkynes:
        - _[Melt Boil Color Smell Toxic]
        - 2≡[-84 -80.8 TRA Garlic X*]
        - 3≡[-103 -23.2 - - -]
        - 4≡[-125.7 8.1 TRA Garlic -]
        - 5≡[-106 40 - - -]
        - 6≡[-131 70 - - -]
        - 7≡[-81 100 - - -]
        - 8≡[-42.6 128 - - -]
        - 9≡[-50 150 - - -]
        - 10≡[-44 174 - - -]
      - $T Arenes:
        - ~~1[5.5 80.1 - - C+R]
        - (1)~~1[-95 110.6 TRA Petroleum F+CED*]
        - (1,2-1)~~1[-25 135 - - D+...]
        - (1,3-1)~~1[-95 110.6 TRA Petroleum F+CED*]
        - ~~2[80.3 218 W+CR PO -]
        - ~~3[217.5 340 TRA - *]
        - ~~5[179 495 - - *]
        - 2~~1[155 251 W+S Medical *]
      - Haloalkane
      - Alcohols
      - Phenols
      - Aldehydes
      - Ketones
      - Carboxylic acids
      - Esters
      - Ethers
      - Amines
      - Thiols
      - Disulfides
      - Nitro compounds
  - $S Biochemistry:
    - Cell Biology:
      - Cells
      - Cell types
    - Genetics
    - Biomolecules:
      - Carbohydrates
      - Lipids
      - Proteins
      - Nucleic acids
    - Metabolism:
      - General metabolic pathways
      - Cellular respiration
      - Photosynthesis
      - Replication
      - Transcription
      - Translation
  - $S Biology:
    - Plants and fungi
    - Physiology
`;
